### ISSUE TITLE
The face cannot be detected when I infer my own input video. 

### ISSUE THREAD

**Issue by AndrewDing616** [Weizhi-Zhong/IP_LAP#31]
Thank for your great work!
But when I run the inference_single.py using my own video, the code cannot work. It show:

`Traceback (most recent call last):
  File "inference_single.py", line 509, in <module>
    full = merge_face_contour_only(original_background, T_input_frame[2], T_ori_face_coordinates[2][1],fa)   #(H,W,3)
  File "inference_single.py", line 145, in merge_face_contour_only
    preds = fa.get_landmarks(input_img)[0]  # 68x2
TypeError: 'NoneType' object is not subscriptable`

So, I wonder how to solve the problem, tks again!

**Comment by yaserabdelaziz** [comment]
I think having a more zoomed-in video on the face might work. IP LAP uses MediaPipe's face landmark detection and this requires the face to be zoomed-in to work.

**Comment by AndrewDing616** [comment]
> 

Thanks for your reply！
